### ISSUE TITLE
PyPi Package not up to date

### ISSUE THREAD

**Issue by marcmaliar** [alanlujan91/multinterp#34]
**Describe the bug**

PyPi package is not up to date. 

Earlier version does not have utilities.py and safe import of backends (running without an optional backend like cupy).

**To Reproduce**

1. pip install multinterp
2. Try to run Warped2D Jupyter Notebook

Alternatively
1. Download tar gz from PyPi
2. Verify that utilities.py is not present

**Expected behavior** 

Jupyter Notebook runs without problems

**Screenshots**

<img width="1001" alt="Screenshot 2024-05-15 at 12 54 02 PM" src="https://github.com/alanlujan91/multinterp/assets/16566880/2f78bf7b-933c-43fa-a5ed-de7f2cb0235b">
Cupy not in requirements.txt
<img width="801" alt="Screenshot 2024-05-15 at 12 53 30 PM" src="https://github.com/alanlujan91/multinterp/assets/16566880/4bcb1074-6863-406f-85be-bcab1d2ee9f1">

**Desktop:**
- OS: MacOS

**Comment by marcmaliar** [comment]
I can't even download a version from here because _version not defined:
<img width="1001" alt="Screenshot 2024-05-21 at 8 25 53 PM" src="https://github.com/alanlujan91/multinterp/assets/16566880/06d44812-f33a-410d-aa5b-8b17df0f0912">

**Comment by alanlujan91** [comment]
once you clone this repo, have you done `pip install -e .` ?

That should install the repo for development and create `_version` which is dynamically generated.

**Comment by marcmaliar** [comment]
Ok - did not know this before

**Comment by alanlujan91** [comment]
yes, I need to write that in the documentation
